import { createRequire } from 'node:module'
import { readFileSync, writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'

/* The one source the list, the names and the marks all come from; everything is
   inlined, so none of these packages is a runtime dependency. Run
   `bun run countries:generate` — src/lib/countries.test.ts fails on drift. */

const require = createRequire(import.meta.url)

function json<T>(specifier: string): T {
  return JSON.parse(readFileSync(require.resolve(specifier), 'utf8')) as T
}

export interface GeneratedCountry {
  code: string
  name: string
  viewBox: string
  body: string
}

interface Containment {
  supplemental: {
    territoryContainment: Record<
      string,
      { _contains?: Array<string> } | undefined
    >
  }
}
interface CodeMappings {
  supplemental: {
    codeMappings: Record<string, { _numeric?: string } | undefined>
  }
}
interface Territories {
  main: {
    en: {
      localeDisplayNames: { territories: Record<string, string | undefined> }
    }
  }
}

/* Leaves of the M.49 world tree are territories, branches are regions; keeping
   only those CLDR gives an ISO 3166-1 numeric drops AC/CP/DG/EA/IC/TA and EU,
   leaving alpha-2 plus XK (which CLDR numbers 983) at 250. */
function selectableCodes(): Array<string> {
  const containment = json<Containment>(
    'cldr-core/supplemental/territoryContainment.json',
  ).supplemental.territoryContainment
  const codeMappings = json<CodeMappings>(
    'cldr-core/supplemental/codeMappings.json',
  ).supplemental.codeMappings

  const leaves = new Set<string>()
  const walk = (territory: string, seen: Set<string>) => {
    if (seen.has(territory)) return
    seen.add(territory)
    const children = containment[territory]?._contains
    if (!children) leaves.add(territory)
    else for (const child of children) walk(child, seen)
  }
  walk('001', new Set())

  return [...leaves].filter(
    (code) => /^[A-Z]{2}$/.test(code) && codeMappings[code]?._numeric,
  )
}

/* Deterministic across ICU versions, unlike localeCompare: fold the diacritics
   away so Åland sorts under A on every machine that regenerates this. */
function sortKey(name: string): string {
  return name.normalize('NFD').replace(/\p{M}/gu, '').toUpperCase()
}

const SVG_WRAPPER = /^<svg\b[^>]*\bviewBox="([^"]+)"[^>]*>(.*)<\/svg>$/s

export function buildCountries(): Array<GeneratedCountry> {
  const territories = json<Territories>(
    'cldr-localenames-modern/main/en/territories.json',
  ).main.en.localeDisplayNames.territories
  const flags = require('country-flag-icons/string/3x2') as Record<
    string,
    string | undefined
  >

  const countries = selectableCodes().map((code) => {
    const name = territories[code]
    if (!name) throw new Error(`${code}: CLDR has no English name`)
    const svg = flags[code]
    if (!svg) throw new Error(`${code}: country-flag-icons has no 3x2 mark`)
    const parsed = SVG_WRAPPER.exec(svg.trim())
    if (!parsed) throw new Error(`${code}: unparseable flag SVG`)
    return { code, name, viewBox: parsed[1], body: parsed[2] }
  })

  return countries
    .map((country) => ({ country, key: sortKey(country.name) }))
    .sort((a, b) => (a.key < b.key ? -1 : a.key > b.key ? 1 : 0))
    .map(({ country }) => country)
}

const HEADER = '// GENERATED by `bun run countries:generate` — do not edit.\n'

/* Inlining 250 marks distributes a substantial portion of the package, which
   MIT permits only with its notice attached — read it rather than copied, so a
   relicence upstream can't leave a stale notice behind. */
function flagLicenceNotice(): string {
  const licence = readFileSync(
    join(
      dirname(require.resolve('country-flag-icons/package.json')),
      'LICENSE',
    ),
    'utf8',
  )
  return `/*\n  Flag marks are country-flag-icons, redistributed under its licence:\n\n${licence
    .trimEnd()
    .split('\n')
    .map((line) => (line.trim() ? `  ${line.trimEnd()}` : ''))
    .join('\n')}\n*/\n`
}

function write(relative: string, body: string): string {
  const out = new URL(relative, import.meta.url)
  writeFileSync(out, HEADER + body)
  return fileURLToPath(out)
}

function main() {
  const countries = buildCountries()

  const list = write(
    '../src/lib/countries.generated.ts',
    '// ISO 3166-1 alpha-2 + XK, named from CLDR, ordered for a picker.\n\n' +
      'export const COUNTRIES: ReadonlyArray<{ code: string; name: string }> = [\n' +
      countries
        .map(
          (c) =>
            `  { code: ${JSON.stringify(c.code)}, name: ${JSON.stringify(c.name)} },`,
        )
        .join('\n') +
      '\n]\n',
  )

  const marks = write(
    '../src/lib/country-flags.generated.ts',
    flagLicenceNotice() +
      '\n// Inlined without their <svg> wrapper. Server-only: 250 marks must\n' +
      '// never reach the client bundle.\n\n' +
      'export const COUNTRY_FLAGS: Readonly<\n' +
      '  Record<string, { viewBox: string; body: string }>\n' +
      '> = {\n' +
      countries
        .map(
          (c) =>
            `  ${c.code}: {\n` +
            `    viewBox: ${JSON.stringify(c.viewBox)},\n` +
            `    body: ${JSON.stringify(c.body)},\n` +
            `  },`,
        )
        .join('\n') +
      '\n}\n',
  )

  console.log(`wrote ${list} and ${marks} (${countries.length} countries)`)
}

if (process.argv[1] === fileURLToPath(import.meta.url)) main()
