import { createRequire } from 'node:module'
import { readFileSync, writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'
import process from 'node:process'

/* Platform brand marks, inlined from simple-icons so no icon package is a
   runtime dependency. Run `bun run marks:generate` —
   src/links/platforms.test.ts rebuilds and compares, so it fails on drift.

   Each mark is the platform's own glyph outline filled with the platform's own
   published brand colour: a full-colour mark, not a recolouring. The ones whose
   interior detail is knocked out to transparent — YouTube's play triangle,
   Reddit's snoo, Telegram's plane, Instagram's aperture — take that detail from
   whatever sits behind them, which is what forces the plate to be white. */

const require = createRequire(import.meta.url)

const HEADER = '// GENERATED by `bun run marks:generate` — do not edit.\n'

/** The slug in simple-icons, per platform id, and the ink to fill its path
    with. `hex` overrides simple-icons' brand colour where the platform's own
    full-colour mark is not a flat one — see Instagram below. TikTok is absent
    on purpose: its logo is forbidden without written permission, so it ships as
    a wordmark instead. */
const MARKS: ReadonlyArray<{ id: string; slug: string; hex?: string }> = [
  { id: 'youtube', slug: 'siYoutube' },
  { id: 'twitch', slug: 'siTwitch' },
  { id: 'discord', slug: 'siDiscord' },
  { id: 'x', slug: 'siX' },
  // Instagram's full-colour mark is a GRADIENT, and simple-icons carries a
  // single flat brand colour for it. Filling the glyph with that flat colour
  // would be a recolouring of the mark — the exact thing the white plate exists
  // to prevent — and the gradient's own stops are not published anywhere we can
  // cite, so they must not be guessed at. Its mono glyph is a sanctioned
  // alternative in Instagram's own asset pack, so that is what ships: an
  // official form, unmodified, which is the same treatment X takes.
  { id: 'instagram', slug: 'siInstagram', hex: '#000000' },
  { id: 'bluesky', slug: 'siBluesky' },
  { id: 'telegram', slug: 'siTelegram' },
  { id: 'reddit', slug: 'siReddit' },
]

interface SimpleIcon {
  title: string
  hex: string
  path: string
}

function licenceNotice(): string {
  const licence = readFileSync(
    join(dirname(require.resolve('simple-icons/package.json')), 'LICENSE.md'),
    'utf8',
  )
  return `/*\n  Glyph outlines are simple-icons, redistributed under its licence:\n\n${licence
    .trimEnd()
    .split('\n')
    .map((line) => (line.trim() ? `  ${line.trimEnd()}` : ''))
    .join('\n')}\n*/\n`
}

export interface BrandMark {
  id: string
  title: string
  hex: string
  path: string
}

/** Exported so the drift test can rebuild and compare: a simple-icons bump
    must not change a shipped mark without something failing. */
export function buildMarks(): BrandMark[] {
  const icons = require('simple-icons') as Record<
    string,
    SimpleIcon | undefined
  >
  return MARKS.map(({ id, slug, hex }) => {
    const icon = icons[slug]
    if (!icon) throw new Error(`simple-icons has no ${slug}`)
    return {
      id,
      title: icon.title,
      hex: hex ?? `#${icon.hex}`,
      path: icon.path,
    }
  })
}

function main() {
  const marks = buildMarks()

  const out = new URL('../src/links/brand-marks.generated.ts', import.meta.url)
  writeFileSync(
    out,
    HEADER +
      licenceNotice() +
      '\n// 24×24, one path each, inlined without their <svg> wrapper.\n\n' +
      'export const BRAND_MARKS: Readonly<\n' +
      '  Record<string, { title: string; hex: string; path: string }>\n' +
      '> = {\n' +
      marks
        .map(
          (m) =>
            `  ${m.id}: {\n` +
            `    title: ${JSON.stringify(m.title)},\n` +
            `    hex: ${JSON.stringify(m.hex)},\n` +
            `    path: ${JSON.stringify(m.path)},\n` +
            `  },`,
        )
        .join('\n') +
      '\n}\n',
  )
  console.log(`wrote ${fileURLToPath(out)} (${marks.length} marks)`)
}

if (process.argv[1] === fileURLToPath(import.meta.url)) main()
