import { readFileSync, writeFileSync } from 'node:fs'

/* Regenerates src/og/assets/embedded.ts — the OG fonts + static fallback as
   base64 so they load identically in the Nitro server bundle, vitest, and
   standalone bun scripts (Vite's `?inline` breaks under bun; a readFileSync of
   the raw file is dropped by the server bundler). Re-run after changing a font
   or regenerating the fallback: `bun run og:embed`. */

const here = (rel: string) => new URL(rel, import.meta.url)
const b64 = (rel: string) => readFileSync(here(rel)).toString('base64')

const assets: Array<[name: string, file: string]> = [
  ['SAIRA_TTF', '../src/og/assets/fonts/Saira.ttf'],
  ['GOLOS_TTF', '../src/og/assets/fonts/GolosText.ttf'],
  ['FALLBACK_PNG', '../src/og/assets/fallback.png'],
]

const body = assets
  .map(([name, file]) => `export const ${name} = '${b64(file)}'\n`)
  .join('\n')

const out = here('../src/og/assets/embedded.ts')
writeFileSync(
  out,
  `// GENERATED by \`bun run og:embed\` — do not edit by hand.\n` +
    `// OG fonts + fallback as base64; loads everywhere without bundler asset magic.\n\n` +
    body,
)
console.log(`wrote ${out.pathname} (${assets.length} assets)`)
